export const skolor = [
  { value: 'CTH', label: 'Chalmers tekniska högskola' },
  { value: 'HB', label: 'Högskolan i Borås' },
  { value: 'GU', label: 'Göteborgs universitet' },
  { value: 'LU', label: 'Lunds universitet' },
  { value: 'LTU', label: 'Luleå tekniska universitet' },
  { value: 'GIH', label: 'Gymnastik- och idrottshögskolan' },
  { value: 'SLU', label: 'Sveriges Lantbruksuniversitet' },
  { value: 'BTH', label: 'Blekinge tekniska högskola' },
  { value: 'MDH', label: 'Mälardalens högskola' },
  { value: 'HH', label: 'Högskolan i Halmstad' },
  { value: 'ORU', label: 'Örebro universitet' },
  { value: 'KAU', label: 'Karlstads universitet' },
  { value: 'HDA', label: 'Högskolan Dalarna' },
  { value: 'LNU', label: 'Linnéuniversitetet' },
  { value: 'MU', label: 'Malmö universitet' },
  { value: 'KTH', label: 'Kungl. Tekniska högskolan' },
  { value: 'UMU', label: 'Umeå universitet' },
  { value: 'SH', label: 'Södertörns högskola' },
  { value: 'JTH', label: 'Johannelunds teologiska högskola' },
  { value: 'SHH', label: 'Sophiahemmet Högskola' },
  { value: 'HS', label: 'Högskolan i Skövde' },
  { value: 'KF', label: 'Konstfack' },
  { value: 'KI', label: 'Karolinska institutet' },
  { value: 'EHS', label: 'Enskilda Högskolan Stockholm' },
  { value: 'NMI', label: 'Newmaninstitutet' },
  { value: 'JU', label: 'Jönköping University' },
  { value: 'FHS', label: 'Försvarshögskolan Stockholm' },
  { value: 'MIU', label: 'Mittuniversitetet' },
  { value: 'KMH', label: 'Kungliga Musikhögskolan i Stockholm' },
  { value: 'LIU', label: 'Linköpings universitet' },
  { value: 'HKR', label: 'Högskolan Kristianstad' },
  { value: 'SU', label: 'Stockholms universitet' },
  { value: 'ESH', label: 'Ersta Sköndal Bräcke högskola' },
  { value: 'RKH', label: 'Röda korsets högskola' },
  { value: 'HV', label: 'Högskolan Väst' },
  { value: 'HIG', label: 'Högskolan i Gävle' },
  { value: 'UU', label: 'Uppsala universitet' },
  { value: 'HHS', label: 'Handelshögskolan i Stockholm' },
];

export const amnesOmraden = [
  { value: 'juridik', label: 'Juridik' },
  { value: 'medicin', label: 'Medicin' },
  { value: 'läkare', label: 'Läkare' },
  { value: 'psykologi', label: 'Psykologi' },
  { value: 'sociologi', label: 'Sociologi' },
  { value: 'kriminologi', label: 'Kriminologi' },
  { value: 'ekonomi', label: 'Ekonomi' },
  { value: 'beteendevetenskap', label: 'Beteendevetenskap' },
  { value: 'vård', label: 'Vård' }, //sjuksköterskeprogrammet
  { value: 'arkitektur', label: 'Arkitektur' },
  { value: 'personalvetenskap', label: 'Personalvetenskap' },
  { value: 'datateknik', label: 'Datateknik' },
  { value: 'programmering', label: 'Programmering' },
  { value: 'djur', label: 'Djur' },
  { value: 'datavetenskap', label: 'Datavetenskap' },
  { value: 'systemvetenskap', label: 'Systemvetenskap' },
  { value: 'it', label: 'IT' },
  { value: 'tandläkare', label: 'Tandläkare' },
  { value: 'fysioterapi', label: 'Fysioterapi' },
];

export const platser = [
  { value: 'Sundsvall, Östersund', label: 'Sundsvall, Östersund' },
  { value: 'Karlstad', label: 'Karlstad' },
  { value: 'Växjö', label: 'Växjö' },
  { value: 'Borås', label: 'Borås' },
  { value: 'Jönköping', label: 'Jönköping' },
  { value: 'Halmstad', label: 'Halmstad' },
  { value: 'Borlänge, Falun', label: 'Borlänge, Falun' },
  { value: 'Örebro', label: 'Örebro' },
  { value: 'Malmö', label: 'Malmö' },
  { value: 'Luleå', label: 'Luleå' },
  { value: 'Gävle', label: 'Gävle' },
  { value: 'Kristianstad', label: 'Kristianstad' },
  { value: 'Göteborg', label: 'Göteborg' },
  { value: 'Trollhättan', label: 'Trollhättan' },
  { value: 'Umeå', label: 'Umeå' },
  { value: 'Karlskrona', label: 'Karlskrona' },
  { value: 'Uppsala', label: 'Uppsala' },
  { value: 'Stockholm', label: 'Stockholm' },
  { value: 'Västerås, Eskilstuna', label: 'Västerås, Eskilstuna' },
  { value: 'Skövde', label: 'Skövde' },
  { value: 'Linköping', label: 'Linköping' },
  { value: 'Lund', label: 'Lund' },
];

export const fakeData1 = [
  { name: 'Läkarprogrammet', school: 'Karolinska institutet' },
  { name: 'Juristprogrammet', school: 'Uppsala universitet' },
  { name: 'Läkarprogrammet', school: 'Lunds universitet' },
  { name: 'Psykologprogrammet', school: 'Stockholms universitet' },
  { name: 'Juristprogrammet', school: 'Lunds universitet' },
  { name: 'Juristprogrammet', school: 'Stockhoms universitet' },
  { name: 'Arkitektutbildningen', school: 'Kungliga Tekniska Högskolan' },
  { name: 'Business & Economics', school: 'Handelshögskolan i Stockholm' },
  { name: 'Civilingenjörsutbildning i Industriell Ekonomi', school: 'Kungliga Tekniska Högskolan' },
  { name: 'Ekonomikandidatsprogrammet', school: 'Stockholms universitet' },
]

export const fakeData2 = [
  { program: 'Läkarprogrammet', skola: 'KI' },
  { program: 'Juristprogrammet', skola: 'UU' },
  { program: 'Läkarprogrammet', skola: 'LU' },
  { program: 'Psykologprogrammet', skola: 'SU' },
  { program: 'Juristprogrammet', skola: 'LU' },
  { program: 'Juristprogrammet', skola: 'SU' },
  { program: 'Arkitektutbildningen', skola: 'KTH' },
  { program: 'Business & Economics', skola: 'HHS' },
  { program: 'Civilingenjörsutbildning i Industriell Ekonomi', skola: 'KTH' },
  { program: 'Ekonomikandidatsprogrammet', skola: 'SU' },
]