import { blue, neutral, yellow, green, red, beige, grey, background, black } from "./colors";
import { primaryFont, typeScale } from "./typography";

export const defaultTheme = {
  primary100: blue[100],
  primary200: blue[200],
  primary300: blue[300],
  primary400: blue[400],
  primary500: blue[500],
  primaryFont: primaryFont,
  primaryText: neutral[600],
  primaryTextInverted: neutral[100],
  neutral100: neutral[100],
  neutral200: neutral[200],
  neutral300: neutral[300],
  neutral400: neutral[400],
  neutral500: neutral[500],
  neutral600: neutral[600],
  success100: green[100],
  success200: green[200],
  warning100: yellow[100],
  warning200: yellow[200],
  error100: red[100],
  error200: red[200],
  beige100: background[100],
  black100: black[100],
  grey100: grey[100],
  background: background['FbGrey'],
  white: background['white'],
  fs: {
    h1xl: typeScale.header1XLarge,
    h1l: typeScale.header1Large,
    h1m: typeScale.header1Medium,
    h1s: typeScale.header1Small,
    h2l: typeScale.header2Large,
    h2m: typeScale.header2Medium,
    h2s: typeScale.header2Small,
    h3l: typeScale.header3Large,
    h3m: typeScale.header3Medium,
    h3s: typeScale.header3Small,
    h4l: typeScale.header4Large,
    h4m: typeScale.header4Medium,
    h4s: typeScale.header4Small,
    h5l: typeScale.header5Large,
    h5m: typeScale.header5Medium,
    h5s: typeScale.header5Small,
    ps: typeScale.paragraphSmall,
    pm: typeScale.paragraphMedium,
    pl: typeScale.paragraphLarge,
    helperText: typeScale.helperText,
    copyrightText: typeScale.copyrightText
  }
}